import argparse
import json
import os
import logging
from pathlib import Path
import boto3
from datetime import datetime
from botocore.exceptions import ClientError

# Professional logging for presentation
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

def get_s3_client(use_localstack: bool):
    """Returns a boto3 client configured for LocalStack or AWS."""
    if use_localstack:
        return boto3.client(
            's3',
            endpoint_url="http://localhost:4566",
            aws_access_key_id="test",
            aws_secret_access_key="test",
            region_name="us-east-1"
        )
    return boto3.client('s3')

def build_manifest(folder: Path, bucket: str, prefix: str):
    # Looking for .onnx slices generated by your 2_slice_model.py script
    files = sorted([p.name for p in folder.glob('*.onnx')])
    if not files:
        logger.error(f"No .onnx files found in {folder}")
        return None
    
    prefix_clean = prefix.rstrip('/')
    keys = [f'{prefix_clean}/{fname}' for fname in files]
    
    manifest = {
        'created_at': datetime.now().isoformat() + 'Z',
        'bucket': bucket,
        'prefix': prefix_clean,
        'slices': keys,
        'count': len(keys),
    }
    return manifest

def upload_manifest(manifest: dict, bucket: str, prefix: str, use_localstack: bool):
    s3 = get_s3_client(use_localstack)
    
    # Ensure bucket exists
    try:
        s3.head_bucket(Bucket=bucket)
    except ClientError:
        if use_localstack:
            logger.info(f"Creating bucket '{bucket}' in LocalStack...")
            s3.create_bucket(Bucket=bucket)
        else:
            raise

    manifest_body = json.dumps(manifest, indent=2)
    key = prefix.rstrip('/') + '/manifest.json'
    
    logger.info(f"Uploading manifest to s3://{bucket}/{key}...")
    s3.put_object(
        Bucket=bucket, 
        Key=key, 
        Body=manifest_body.encode('utf-8'), 
        ContentType='application/json'
    )
    return key

if __name__ == '__main__':
    p = argparse.ArgumentParser(description='Create and Upload ONNX Slice Manifest')
    p.add_argument('--folder', type=str, default='slices', help='Local folder containing ONNX slices')
    p.add_argument('--bucket', type=str, required=True, help='S3 bucket name')
    p.add_argument('--prefix', type=str, default='mobilenetv3/slices/', help='S3 path prefix')
    p.add_argument('--aws', action='store_true', help='Use real AWS instead of LocalStack')
    args = p.parse_args()

    folder_path = Path(args.folder)
    if not folder_path.exists():
        logger.error(f"Folder not found: {folder_path}")
        exit(1)

    # 1. Build the manifest data
    manifest_data = build_manifest(folder_path, args.bucket, args.prefix)
    if not manifest_data:
        exit(1)

    # 2. Save locally for inspection
    local_manifest = folder_path / 'manifest.json'
    with open(local_manifest, 'w', encoding='utf-8') as f:
        json.dump(manifest_data, f, indent=2)
    logger.info(f"Wrote local manifest to: {local_manifest}")

    # 3. Upload to LocalStack/AWS
    try:
        use_ls = not args.aws
        s3_key = upload_manifest(manifest_data, args.bucket, args.prefix, use_ls)
        logger.info("Upload Successful!")
    except Exception as e:
        logger.error(f"Upload failed: {e}")