version: "3.8"

services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:latest  # Pro features are enabled here
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - LOCALSTACK_AUTH_TOKEN=ls-XOVu5588-pOhe-3670-coPA-yEkUKIZU6e33
      - SERVICES=s3,iam,lambda,sts,stepfunctions
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"